export default defineAppConfig({
  data: {
    nickname: 'SolsticeLeaf',
    mail: 'me@sleaf.dev',
  },
  images: {
    astronautImg: 'https://s3.sleaf.dev/portfolio/astronaut.webp',
    errorImg: 'https://s3.sleaf.dev/portfolio/error.webp',
  },
  gitlab: {
    calendarUrl: 'https://git.sleaf.dev/users/solsticeleaf/calendar.json',
  },
  icons: {
    nav_home: 'mingcute:home-3-fill',
    nav_projects: 'mingcute:server-2-fill',
    nav_donate: 'mingcute:pig-money-fill',
    nav_lang: 'mingcute:globe-2-fill',
    email: 'mingcute:mail-fill',
    discord: 'mingcute:discord-fill',
    read_more: 'mingcute:layout-bottom-open-fill',
    download: 'mingcute:download-3-fill',
    donate: 'mingcute:hand-card-fill',
    donate_success: 'mingcute:hand-heart-line',
    donate_pay: 'mingcute:card-pay-fill',
    back_home: 'mingcute:left-fill',
  },
  tools: ['kotlin', 'java', 'micronaut', 'spring', 'typescript', 'javascript', 'nuxtjs', 'gradle', 'mysql', 'mongodb', 'postgresql', 'redis'],
  currencies: [
    { id: 1, name: 'USD', symbol: '$', default: 2 },
    { id: 2, name: 'EUR', symbol: '€', default: 2 },
    { id: 3, name: 'RUB', symbol: '₽', default: 200 },
    { id: 4, name: 'KZT', symbol: '₸', default: 1000 },
    { id: 5, name: 'UAH', symbol: '₴', default: 80 },
    { id: 6, name: 'GBP', symbol: '£', default: 2 },
    { id: 7, name: 'TRY', symbol: '₺', default: 70 },
    { id: 8, name: 'CNY', symbol: '¥', default: 14 },
    { id: 9, name: 'INR', symbol: '₹', default: 170 },
    { id: 10, name: 'JPY', symbol: '¥', default: 310 },
    { id: 11, name: 'PHP', symbol: '₱', default: 115 },
    { id: 12, name: 'THB', symbol: '฿', default: 70 },
    { id: 13, name: 'VND', symbol: '₫', default: 50 },
    { id: 14, name: 'AMD', symbol: '֏', default: 780 },
    { id: 15, name: 'AZN', symbol: '₼', default: 3 },
  ],
});
